### ISSUE TITLE
Goal: be able to implement the user-provided service broker using this project

### ISSUE THREAD

**Issue by pmorie** [openshift/open-service-broker-sdk#10]
I was thinking about the experience we should converge on in this project over the weekend and came up with this as a goal:

I should be able to implement the [user-provided service broker](https://github.com/kubernetes-incubator/service-catalog/tree/master/contrib/cmd/user-broker) using this project and it should be easy, where easy is defined as less than 500 loc (crummy characterization, but it came to mind).

**Comment by bparees** [comment]
seems not insane.  w/o looking at the user provided service broker too closely, i'd speculate that this project is already there, though, or at least really close.

**Comment by pmorie** [comment]
It would certainly be possible to implement it from an 80% standpoint.  The gaps I would like to close are things like:

- idempotency
- automatic conflict detection
- pending operation checks (ie, reject a bind while an async update is in progress)

We are just getting to a point in the catalog incubator where we're beginning to be concerned with full compliance with the spec, and I would like for `make` in this project to result in a compliant broker, or at least help you build a compliant broker without having to intimately understand all the subtleties involved.
