### ISSUE TITLE
reason to commit vendor directory?

### ISSUE THREAD

**Issue by jmrodri** [openshift/open-service-broker-sdk#11]
Is there a reason we commit the vendor directory? On our broker, we simply commit the `glide.yaml` and `glide.lock` file and added vendor to `.gitignore`.

**Comment by bparees** [comment]
makes it less painful to bootstrap a new dev environment, just following the same practices we use in origin (admittedly we use godeps, not glide there).

**Comment by bparees** [comment]
(in theory it also protects us against someone rewriting history in their repo, or removing their repo entirely)

**Comment by bparees** [comment]
the service catalog (which uses glide) also follows this pattern, so i'm closing this.
https://github.com/kubernetes-incubator/service-catalog/tree/master/vendor
