### ISSUE TITLE
Instructions/tests for running the service catalog in front of the broker SDK

### ISSUE THREAD

**Issue by maleck13** [openshift/open-service-broker-sdk#19]
A service broker is intended to run behind a service catalog which adapts and passes on requests to perform the various actions such as provision and bind. It would useful to be able to test and verify that the broker developed using this sdk was successfully able to integrate with the catalog. To enable this it should be made simple to set up the catalog and register the broker with it. It would then be very useful to have a set of "black box" test that would execute against the broker and validate it was responding as expected. It would also be good if these tests were easy to extend and modify so that they could remain useful throughout the development process.

**Comment by pmorie** [comment]
Agree 100% with this.

**Comment by jmrodri** [comment]
The ansible service broker has done work with getting a catalog to run with our broker.

**Comment by pmorie** [comment]
I'm sorry, I read this the wrong way.  Making a way to deploy the catalog is not a goal for this repo - it will be impossible to keep up to date and we have far too many ways of orchestrating things already.

It's already extremely easy to deploy the catalog onto k8s with helm, and we're working toward support for `oc cluster up` to deploy the catalog.

I initially read this as 'add instructions for how to register brokers built from this SDK in the service-catalog', which is a thing I want.

**Comment by pmorie** [comment]
I do want a conformance suite for the catalog, that is a goal, though not one of this project.

**Comment by bparees** [comment]
closing this, opened https://github.com/openshift/open-service-broker-sdk/issues/26 for the registration requirement.
