### ISSUE TITLE
openshift/brokersdk references?

### ISSUE THREAD

**Issue by eriknelson** [openshift/open-service-broker-sdk#2]
Trying to get up and running and I'm seeing a lot of unknown references to `github.com/openshift/brokersdk`. Should these be updated to `github.com/openshift/open-service-broker-sdk`?

**Comment by pmorie** [comment]
Yes.  Go for it.

**Comment by bparees** [comment]
i'll take care of it, thanks.  sorry, bad decision to do a last minute renaming :(
