### ISSUE TITLE
Kubernetes translation of roles.yaml

### ISSUE THREAD

**Issue by maleck13** [openshift/open-service-broker-sdk#20]
The roles in https://github.com/openshift/open-service-broker-sdk/blob/master/test-scripts/resources/roles.yaml do not currently work in a standalone Kubernetes cluster, this is because the it uses OpenShift specific constructs. In order to allow this SDK to work for both Kubernetes and OpenShift, these roles need to be translated into the ```rbac``` API https://kubernetes.io/docs/admin/authorization/rbac/

**Comment by bparees** [comment]
we should supply both sets of roles, and an install script for each set. (installl-openshift, install-k8s) or make it an argument to the install script.

**Comment by enj** [comment]
Openshift has conversion functions for converting between origin / kube RBAC.  You should be able to automate the generation of one from the other.

**Comment by bparees** [comment]
@enj are those conversion functions only available in code, or do we actually have cli invocations for doing it?

**Comment by enj** [comment]
[Code only](https://github.com/openshift/origin/blob/6858e4fdf1d14303b7f48e36ba238ab424b3de64/pkg/cmd/server/bootstrappolicy/policy.go#L1262-L1300).

**Comment by maleck13** [comment]
I believe I have a working translation now, will make a pr shortly

**Comment by maleck13** [comment]
@bparees The translation I created yesterday evening is working well on my K8 cluster. A suggestion for adding it is to add a new install directory that would look like this 

```
install/
├── kubernetes  #roles.yaml, service.yaml etc...
└── openshift #template.yaml roles.yaml
```

another option would be to keep the common pieces at the install level and have the specific pieces in the directories?

**Comment by bparees** [comment]
@maleck13 yeah i'd rather keep the common stuff together and then subdirs for the specific stuff.
