### ISSUE TITLE
test-scripts/shared.sh:  Fails to get broker service ip

### ISSUE THREAD

**Issue by copejon** [openshift/open-service-broker-sdk#30]
```
root@kube /opt/go/src/open-service-broker-sdk/test-scripts master
# ./provision.sh
Error from server (NotFound): services "brokersdk" not found
```

The problem is in `shared.sh`, line 17.  Looks like this command just needs the namespace specified.  Doing so fixes the issue.

```
broker_service_ip=`oc get svc brokersdk -o jsonpath={.spec.clusterIP}\`
```

**Comment by bparees** [comment]
there is an undocumented assumption that you're running this stuff while your client is on the brokersdk namespace.

(for that matter the command should probably use kubectl instead of oc).

**Comment by copejon** [comment]
Thanks, I'll close this out then.
